Feat/service interfaces
hbagdi/go-kong pull request #14
Opened 2019-09-30 21:34 UTC by ciroque

Addresses Issue #13 

Uses the go generate command to run [vburenin's ifacemaker](https://github.com/vburenin/ifacemaker) that generates files containing interfaces based on the structs.

Also includes a script that writes the go:generate comment to each of the service files.

The general idea is that users of the library can now create mocks of the various Services. This ensures testing boundaries within a given code base coincide with the use of the library. That is, tests in users of the library test only there code and can provide success / failure scenarios by mocking the required service and focus on the "Class Under Test".

2019-09-30 21:36 UTC, ciroque commented
Hi @hbagdi ,

I was able to carve out some time to work on this. Finding the ifacemaker library was great. Made this pretty straightforward to accomplish.

Let me know if you would like me to change anything about the way this is done.

Thanks!

r/Steve

2019-09-30 23:15 UTC, hbagdi commented
I had a brief look at this but I'm liking it so far! Nice job!

One key thing that is missing is to have a script to verify if the code-gen is up-to-date or not.
And then also integrate that with CI so that it can catch when a method is added to a service but not to the corresponding Interface.

2019-10-01 18:25 UTC, ciroque commented
Would it be enough to run `go generate` in the travis.yml, like this:

```
before_install:
  - go generate ./kong
```

(I have not tested that yet)

2019-10-01 18:39 UTC, ciroque commented
Oh interesting. I found this command that would fail the build if the interfaces were out of sync:

`go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)`

Lifted from: https://github.com/google/go-github/blob/master/.travis.yml#L24

It would not automatically generate the new interfaces, but would kick back to the dev to run `go generate` and commit the interface changes...

cool?

2019-10-06 19:10 UTC, hbagdi commented
Yes, that would work.
All we need is to ensure that CI fails a commit if there is a function added onto the struct but it is not added  in the interface.

2019-10-06 19:22 UTC, hbagdi requested changes
Please make sure that CI is running and detecting the changes.

2019-10-06 19:22 UTC, hbagdi commented on .gitignore
> +/.idea/
Please remove this.
You can add this to your global gitignore file:
https://davidwalsh.name/global-gitignore

2019-10-06 19:22 UTC, hbagdi commented on hack/generate-ifacemaker-comments.sh
> +extractStructName() {
Where is this script being used?

2019-10-06 19:22 UTC, hbagdi commented on kong/acl_service.go
> +
This is little bit of nitpick but I think it's important.
Can we move this just above the the declaration of the service?
This helps when someone is reading only part of the code or duplicating this into another service.

This comment applies to all the generate comments.

2019-10-17 22:48 UTC, hbagdi commented
@ciroque Friendly ping. This is almost there.

2019-12-04 06:13 UTC, hbagdi commented
@ciroque Friendly ping.

2019-12-31 22:06 UTC, hbagdi commented
@ciroque Another friendly ping. :)

2020-05-15 20:28 UTC, hbagdi commented
This would have been an amazing addition to the project. If someone else wants to take this up, please feel free!

2020-05-20 18:06 UTC, closed without merging